language: node_js
node_js:
  - "4.0"
script:
  - echo "Deploying!"
before_install: 
  - cd fixbot/web/
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN